### ISSUE TITLE
Test V3 - 2016 : Créer un dossier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/roundcube_laclasse_skin#3]
Après avoir créé un dossier dans la boite de réception, l'utilisateur perd le bandeau ENT lui permettant de revenir sur les autres applications

**Comment by dlacroix** [comment]
C'est un problème de CSS dans laclasse-portail. Corrigé par Gwenhaël et en production.

**Comment by TestsCGI** [comment]
Test OK
