### ISSUE TITLE
Test V3 - 2016 : Déplacer vers Pourriels

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/roundcube_laclasse_skin#4]
Lorsque l'utilisateur déplace un mail dans le dossier Pourriels, un message d'erreur s'affiche et le mail n'est pas déplacé : http://screencast.com/t/TbEgCA6zD9Rw

**Comment by dlacroix** [comment]
Il s'agit d'une erreur de configuration. Plus exactement, depuis Ubuntu 16.04, l'antispam DSPAM n'est plus supporté car il n'y a plus de mainteneur pour ce projet. Du coup il est retiré de Debian et de tous ses dérivés. Du coup, l'anti-spam a été retiré mais il resté un résidu de configuration sur ce dossier spécial. C'est corrigé et cela ne doit plus générer d'erreur. D'ailleurs pour les nouvelles boîtes, il ne devrait même plus y avoir de dossier de SPAM.

**Comment by TestsCGI** [comment]
Test OK
