### ISSUE TITLE
Test V3 - 2016 : Libellés pas traduits

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/roundcube_laclasse_skin#6]
Dans le paramétrage des dossiers, les libellés ne sont pas traduits : http://screencast.com/t/W0LD1vhHl

**Comment by dlacroix** [comment]
Il n'y a pas de raison de traduire cela. Il ne s'agit pas d'un "libellé" mais du nom d'un dossier. Le nom des dossiers dépend des utilisateurs mais surtout des applications qu'ils utilisent.
Bref il n'y a pas de bug mais peut être des dossiers qui ne servent à rien créer à cause d'une reprise de compte. Merci de me donner le compte pour que j'aille faire le ménage si nécessaire.
